# Generated by Django 6.0 on 2026-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories_factor',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=5),
        ),
    ]
