# Generated by Django 6.0 on 2026-01-07 17:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_main_image_exerciseimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/thumbnails/'),
        ),
        migrations.CreateModel(
            name='ExerciseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exercises/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov', 'avi'])])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='workouts.exercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ExerciseImage',
        ),
    ]
