# Generated by Django 6.0 on 2026-01-23 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_exerciseentry_calories_factor_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseentry',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.exercise'),
        ),
    ]
