# Generated by Django 6.0 on 2026-01-23 17:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_exerciseentry_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.DecimalField(choices=[(Decimal('1.2'), 'Сидячий (без тренувань)'), (Decimal('1.375'), 'Легкий (1-3 тренування/тиждень)'), (Decimal('1.55'), 'Помірний (3-5 тренувань/тиждень)'), (Decimal('1.725'), 'Активний (6-7 тренувань/тиждень)'), (Decimal('1.9'), 'Дуже активний (фізична робота + спорт)')], decimal_places=3, default=Decimal('1.2'), max_digits=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('LOSE', 'Схуднення (-500 ккал)'), ('MAINTAIN', 'Підтримання ваги'), ('GAIN', 'Набір маси (+500 ккал)')], default='MAINTAIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_calories',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
